/*
  -- Dave Skura, 2023
*/

CREATE OR REPLACE TABLE `lt-dia-lake-sbx`.daves_dataset.test_sap_konp_snpsht (

  snapshot_time TIMESTAMP OPTIONS(description='Time of the Snaphot. I.E. Snapshot time of load to this table'),
  operation STRING OPTIONS(description='INSERT,UPDATE,DELETE,BEFOREIMAGE'),
  mandt STRING OPTIONS(description='Client'),
  knumh STRING OPTIONS(description='Condition record number'),
  kopos STRING OPTIONS(description='Sequential number of the condition'),
  kappl STRING OPTIONS(description='Application'),
  kschl STRING OPTIONS(description='Condition type'),
  knumt STRING OPTIONS(description='Number of texts'),
  stfkz STRING OPTIONS(description='Scale type'),
  kzbzg STRING OPTIONS(description='Scale basis indicator'),
  kstbm STRING OPTIONS(description='Condition scale quantity'),
  konms STRING OPTIONS(description='Condition scale unit of measure'),
  kstbw STRING OPTIONS(description='Scale value'),
  konws STRING OPTIONS(description='Scale currency'),
  krech STRING OPTIONS(description='Calculation type for condition'),
  kbetr STRING OPTIONS(description='Rate (condition amount or percentage) where no scale exists'),
  konwa STRING OPTIONS(description='Rate unit (currency or percentage)'),
  kpein STRING OPTIONS(description='Condition pricing unit'),
  kmein STRING OPTIONS(description='Condition unit'),
  prsch STRING OPTIONS(description='Scale group'),
  kumza STRING OPTIONS(description='Numerator for converting condition units to base units'),
  kumne STRING OPTIONS(description='Denominator for converting condition units to base units'),
  meins STRING OPTIONS(description='Base unit of measure'),
  mxwrt STRING OPTIONS(description='Lower limit of the condition rate/amount'),
  gkwrt STRING OPTIONS(description='Upper limit for the condition rate'),
  pkwrt STRING OPTIONS(description='Planned condition value'),
  fkwrt STRING OPTIONS(description='Cumulative guaranteed discount                   (not used)'),
  rswrt STRING OPTIONS(description='Accumulated accruals values                       (not used)'),
  kwaeh STRING OPTIONS(description='Condition currency (for cumulation fields)'),
  ukbas STRING OPTIONS(description='Planned condition basis'),
  kznep STRING OPTIONS(description='Condition exclusion indicator'),
  kunnr STRING OPTIONS(description='Customer number'),
  lifnr STRING OPTIONS(description='Account number of vendor or creditor'),
  mwsk1 STRING OPTIONS(description='Tax on sales/purchases code'),
  loevm_ko STRING OPTIONS(description='Deletion indicator for condition item'),
  zaehk_ind STRING OPTIONS(description='Condition item index'),
  bomat STRING OPTIONS(description='Article for rebate settlement'),
  kbrue STRING OPTIONS(description='Accrual amount'),
  kspae STRING OPTIONS(description='Rebate was set up retroactively'),
  bosta STRING OPTIONS(description='Condition record status (rebate)'),
  knuma_pi STRING OPTIONS(description='Promotion'),
  knuma_ag STRING OPTIONS(description='Sales deal'),
  knuma_sq STRING OPTIONS(description='Sales quote'),
  valtg STRING OPTIONS(description='Additional value days'),
  valdt STRING OPTIONS(description='Fixed value date'),
  zterm STRING OPTIONS(description='Terms of payment key'),
  anzauf STRING OPTIONS(description='Maximum number of sales orders per condition record'),
  mikbas STRING OPTIONS(description='Minimum condition base value'),
  mxkbas STRING OPTIONS(description='Maximum condition base value'),
  komxwrt STRING OPTIONS(description='Maximum condition value'),
  klf_stg STRING OPTIONS(description='Number of incremental scale'),
  klf_kal STRING OPTIONS(description='Scale number for pricing'),
  vkkal STRING OPTIONS(description='Sales price calculation: relevant to pricing'),
  aktnr STRING OPTIONS(description='Promotion'),
  knuma_bo STRING OPTIONS(description='Agreement (subsequent settlement)'),
  mwsk2 STRING OPTIONS(description='Withholding tax code'),
  vertt STRING OPTIONS(description='Contract type'),
  vertn STRING OPTIONS(description='Contract number'),
  vbewa STRING OPTIONS(description='Flow type'),
  mdflg STRING OPTIONS(description='Indicator: matrix maintenance'),
  kfrst STRING OPTIONS(description='Release status'),
  uasta STRING OPTIONS(description='Status of business volume comparison for a condition'),
  __bev1__ecrtt STRING OPTIONS(description=''),
  __bev1__ecrtn STRING OPTIONS(description=''),
  __bev1__ecewa STRING OPTIONS(description=''),
  __lclcdp__billback STRING OPTIONS(description=''),
  __lclcdp__category STRING OPTIONS(description=''),
  __lclcdp__cus_list STRING OPTIONS(description=''),
  zzkbeln STRING OPTIONS(description='Number of pricing document'),
  zzkbelp STRING OPTIONS(description='Item number of pricing document'),
  rec_cre_tms TIMESTAMP OPTIONS(description='Record create timestamp'),
  file_name STRING OPTIONS(description='Source File Name ')
)
CLUSTER BY mandt,knumh,kopos
OPTIONS(
  description='Only the latest rows from sap_konp_hist since last run.  Updated with procedure do_update_test_snpsht()'
);